### ISSUE TITLE
Figure out how to remove 'Gradle-aware Make' before task

### ISSUE THREAD

**Issue by ghostbuster91** [elpassion/mainframer-intelij-plugin#4]

**Comment by ghostbuster91** [comment]
I think we can leave it as it is (at least at that point), because the default before task can be configured by user through run configration defaults settings.

**Comment by pawegio** [comment]
Makes sense

**Comment by artem-zinnatullin** [comment]
Just in case, would be nice to not make this plugin Android/Gradle/etc specific but instead universal enough that it could redirect any build command to remote machine through mainframer.

**Comment by ghostbuster91** [comment]
Agree, but
1. We are creating some mvp right know.
2. Once we finish support for gradle/android we will try to expand solution to be more technology agnostic.

**Comment by artem-zinnatullin** [comment]
Got it, ok cool! Watching precisely, will be happy to test once something
shippable be ready!
